service: serverless-todo-app

plugins:
  - serverless-iam-roles-per-function

provider: ${file(./serverless-config/provider.yml)}
functions: ${file(./serverless-config/functions.yml)}
resources: ${file(./serverless-config/resources.yml)}
